# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ude/ude_objects/ude_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ude.ude_objects import ude_side_channel_message_pb2 as ude_dot_ude__objects_dot_ude__side__channel__message__pb2
from ude.ude_objects import ude_empty_message_pb2 as ude_dot_ude__objects_dot_ude__empty__message__pb2
from ude.ude_objects import ude_data_message_pb2 as ude_dot_ude__objects_dot_ude__data__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ude/ude_objects/ude_message.proto',
  package='ude_objects',
  syntax='proto3',
  serialized_pb=_b('\n!ude/ude_objects/ude_message.proto\x12\x0bude_objects\x1a.ude/ude_objects/ude_side_channel_message.proto\x1a\'ude/ude_objects/ude_empty_message.proto\x1a&ude/ude_objects/ude_data_message.proto\"8\n\x15UDEMessageHeaderProto\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xfb\x01\n\x0fUDEMessageProto\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".ude_objects.UDEMessageHeaderProto\x12\x35\n\x08\x65mptyMsg\x18\x02 \x01(\x0b\x32!.ude_objects.UDEEmptyMessageProtoH\x00\x12\x41\n\x0esideChannelMsg\x18\x03 \x01(\x0b\x32\'.ude_objects.UDESideChannelMessageProtoH\x00\x12\x33\n\x07\x64\x61taMsg\x18\x04 \x01(\x0b\x32 .ude_objects.UDEDataMessageProtoH\x00\x42\x05\n\x03msg*7\n\x13UDEMessageTypeProto\x12\t\n\x05\x45MPTY\x10\x00\x12\x0b\n\x07\x43HANNEL\x10\x01\x12\x08\n\x04\x44\x41TA\x10\x02\x62\x06proto3')
  ,
  dependencies=[ude_dot_ude__objects_dot_ude__side__channel__message__pb2.DESCRIPTOR,ude_dot_ude__objects_dot_ude__empty__message__pb2.DESCRIPTOR,ude_dot_ude__objects_dot_ude__data__message__pb2.DESCRIPTOR,])

_UDEMESSAGETYPEPROTO = _descriptor.EnumDescriptor(
  name='UDEMessageTypeProto',
  full_name='ude_objects.UDEMessageTypeProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMPTY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHANNEL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=491,
  serialized_end=546,
)
_sym_db.RegisterEnumDescriptor(_UDEMESSAGETYPEPROTO)

UDEMessageTypeProto = enum_type_wrapper.EnumTypeWrapper(_UDEMESSAGETYPEPROTO)
EMPTY = 0
CHANNEL = 1
DATA = 2



_UDEMESSAGEHEADERPROTO = _descriptor.Descriptor(
  name='UDEMessageHeaderProto',
  full_name='ude_objects.UDEMessageHeaderProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ude_objects.UDEMessageHeaderProto.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ude_objects.UDEMessageHeaderProto.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=235,
)


_UDEMESSAGEPROTO = _descriptor.Descriptor(
  name='UDEMessageProto',
  full_name='ude_objects.UDEMessageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ude_objects.UDEMessageProto.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emptyMsg', full_name='ude_objects.UDEMessageProto.emptyMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sideChannelMsg', full_name='ude_objects.UDEMessageProto.sideChannelMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataMsg', full_name='ude_objects.UDEMessageProto.dataMsg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='ude_objects.UDEMessageProto.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=238,
  serialized_end=489,
)

_UDEMESSAGEPROTO.fields_by_name['header'].message_type = _UDEMESSAGEHEADERPROTO
_UDEMESSAGEPROTO.fields_by_name['emptyMsg'].message_type = ude_dot_ude__objects_dot_ude__empty__message__pb2._UDEEMPTYMESSAGEPROTO
_UDEMESSAGEPROTO.fields_by_name['sideChannelMsg'].message_type = ude_dot_ude__objects_dot_ude__side__channel__message__pb2._UDESIDECHANNELMESSAGEPROTO
_UDEMESSAGEPROTO.fields_by_name['dataMsg'].message_type = ude_dot_ude__objects_dot_ude__data__message__pb2._UDEDATAMESSAGEPROTO
_UDEMESSAGEPROTO.oneofs_by_name['msg'].fields.append(
  _UDEMESSAGEPROTO.fields_by_name['emptyMsg'])
_UDEMESSAGEPROTO.fields_by_name['emptyMsg'].containing_oneof = _UDEMESSAGEPROTO.oneofs_by_name['msg']
_UDEMESSAGEPROTO.oneofs_by_name['msg'].fields.append(
  _UDEMESSAGEPROTO.fields_by_name['sideChannelMsg'])
_UDEMESSAGEPROTO.fields_by_name['sideChannelMsg'].containing_oneof = _UDEMESSAGEPROTO.oneofs_by_name['msg']
_UDEMESSAGEPROTO.oneofs_by_name['msg'].fields.append(
  _UDEMESSAGEPROTO.fields_by_name['dataMsg'])
_UDEMESSAGEPROTO.fields_by_name['dataMsg'].containing_oneof = _UDEMESSAGEPROTO.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['UDEMessageHeaderProto'] = _UDEMESSAGEHEADERPROTO
DESCRIPTOR.message_types_by_name['UDEMessageProto'] = _UDEMESSAGEPROTO
DESCRIPTOR.enum_types_by_name['UDEMessageTypeProto'] = _UDEMESSAGETYPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UDEMessageHeaderProto = _reflection.GeneratedProtocolMessageType('UDEMessageHeaderProto', (_message.Message,), dict(
  DESCRIPTOR = _UDEMESSAGEHEADERPROTO,
  __module__ = 'ude.ude_objects.ude_message_pb2'
  # @@protoc_insertion_point(class_scope:ude_objects.UDEMessageHeaderProto)
  ))
_sym_db.RegisterMessage(UDEMessageHeaderProto)

UDEMessageProto = _reflection.GeneratedProtocolMessageType('UDEMessageProto', (_message.Message,), dict(
  DESCRIPTOR = _UDEMESSAGEPROTO,
  __module__ = 'ude.ude_objects.ude_message_pb2'
  # @@protoc_insertion_point(class_scope:ude_objects.UDEMessageProto)
  ))
_sym_db.RegisterMessage(UDEMessageProto)


# @@protoc_insertion_point(module_scope)
