# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ude/ude_objects/ude_data_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ude/ude_objects/ude_data_message.proto',
  package='ude_objects',
  syntax='proto3',
  serialized_pb=_b('\n&ude/ude_objects/ude_data_message.proto\x12\x0bude_objects\"#\n\x13UDEDataMessageProto\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x62\x06proto3')
)




_UDEDATAMESSAGEPROTO = _descriptor.Descriptor(
  name='UDEDataMessageProto',
  full_name='ude_objects.UDEDataMessageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ude_objects.UDEDataMessageProto.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['UDEDataMessageProto'] = _UDEDATAMESSAGEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UDEDataMessageProto = _reflection.GeneratedProtocolMessageType('UDEDataMessageProto', (_message.Message,), dict(
  DESCRIPTOR = _UDEDATAMESSAGEPROTO,
  __module__ = 'ude.ude_objects.ude_data_message_pb2'
  # @@protoc_insertion_point(class_scope:ude_objects.UDEDataMessageProto)
  ))
_sym_db.RegisterMessage(UDEDataMessageProto)


# @@protoc_insertion_point(module_scope)
