# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ude.ude_objects import ude_message_pb2 as ude_dot_ude__objects_dot_ude__message__pb2


class UDEProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.step = channel.unary_unary(
                '/ude_objects.UDEProto/step',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )
        self.reset = channel.unary_unary(
                '/ude_objects.UDEProto/reset',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )
        self.close = channel.unary_unary(
                '/ude_objects.UDEProto/close',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )
        self.observation_space = channel.unary_unary(
                '/ude_objects.UDEProto/observation_space',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )
        self.action_space = channel.unary_unary(
                '/ude_objects.UDEProto/action_space',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )
        self.side_channel_send = channel.unary_unary(
                '/ude_objects.UDEProto/side_channel_send',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )
        self.side_channel_stream = channel.unary_stream(
                '/ude_objects.UDEProto/side_channel_stream',
                request_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
                response_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                )


class UDEProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def observation_space(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def action_space(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def side_channel_send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def side_channel_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UDEProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
            'close': grpc.unary_unary_rpc_method_handler(
                    servicer.close,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
            'observation_space': grpc.unary_unary_rpc_method_handler(
                    servicer.observation_space,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
            'action_space': grpc.unary_unary_rpc_method_handler(
                    servicer.action_space,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
            'side_channel_send': grpc.unary_unary_rpc_method_handler(
                    servicer.side_channel_send,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
            'side_channel_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.side_channel_stream,
                    request_deserializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
                    response_serializer=ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ude_objects.UDEProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UDEProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ude_objects.UDEProto/step',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ude_objects.UDEProto/reset',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ude_objects.UDEProto/close',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def observation_space(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ude_objects.UDEProto/observation_space',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def action_space(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ude_objects.UDEProto/action_space',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def side_channel_send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ude_objects.UDEProto/side_channel_send',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def side_channel_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ude_objects.UDEProto/side_channel_stream',
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.SerializeToString,
            ude_dot_ude__objects_dot_ude__message__pb2.UDEMessageProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
