# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ude/ude_objects/ude_empty_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ude/ude_objects/ude_empty_message.proto',
  package='ude_objects',
  syntax='proto3',
  serialized_pb=_b('\n\'ude/ude_objects/ude_empty_message.proto\x12\x0bude_objects\"\x16\n\x14UDEEmptyMessageProtob\x06proto3')
)




_UDEEMPTYMESSAGEPROTO = _descriptor.Descriptor(
  name='UDEEmptyMessageProto',
  full_name='ude_objects.UDEEmptyMessageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['UDEEmptyMessageProto'] = _UDEEMPTYMESSAGEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UDEEmptyMessageProto = _reflection.GeneratedProtocolMessageType('UDEEmptyMessageProto', (_message.Message,), dict(
  DESCRIPTOR = _UDEEMPTYMESSAGEPROTO,
  __module__ = 'ude.ude_objects.ude_empty_message_pb2'
  # @@protoc_insertion_point(class_scope:ude_objects.UDEEmptyMessageProto)
  ))
_sym_db.RegisterMessage(UDEEmptyMessageProto)


# @@protoc_insertion_point(module_scope)
