"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions
import ude.ude_objects.ude_data_message_pb2
import ude.ude_objects.ude_empty_message_pb2
import ude.ude_objects.ude_side_channel_message_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___UDEMessageTypeProto = UDEMessageTypeProto
class _UDEMessageTypeProto(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UDEMessageTypeProto.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    EMPTY = UDEMessageTypeProto.V(0)
    CHANNEL = UDEMessageTypeProto.V(1)
    DATA = UDEMessageTypeProto.V(2)
class UDEMessageTypeProto(metaclass=_UDEMessageTypeProto):
    V = typing.NewType('V', builtins.int)
EMPTY = UDEMessageTypeProto.V(0)
CHANNEL = UDEMessageTypeProto.V(1)
DATA = UDEMessageTypeProto.V(2)

class UDEMessageHeaderProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    status: builtins.int = ...
    message: typing.Text = ...

    def __init__(self,
        *,
        status : builtins.int = ...,
        message : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"message",b"message",u"status",b"status"]) -> None: ...
global___UDEMessageHeaderProto = UDEMessageHeaderProto

class UDEMessageProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    @property
    def header(self) -> global___UDEMessageHeaderProto: ...

    @property
    def emptyMsg(self) -> ude.ude_objects.ude_empty_message_pb2.UDEEmptyMessageProto: ...

    @property
    def sideChannelMsg(self) -> ude.ude_objects.ude_side_channel_message_pb2.UDESideChannelMessageProto: ...

    @property
    def dataMsg(self) -> ude.ude_objects.ude_data_message_pb2.UDEDataMessageProto: ...

    def __init__(self,
        *,
        header : typing.Optional[global___UDEMessageHeaderProto] = ...,
        emptyMsg : typing.Optional[ude.ude_objects.ude_empty_message_pb2.UDEEmptyMessageProto] = ...,
        sideChannelMsg : typing.Optional[ude.ude_objects.ude_side_channel_message_pb2.UDESideChannelMessageProto] = ...,
        dataMsg : typing.Optional[ude.ude_objects.ude_data_message_pb2.UDEDataMessageProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"dataMsg",b"dataMsg",u"emptyMsg",b"emptyMsg",u"header",b"header",u"msg",b"msg",u"sideChannelMsg",b"sideChannelMsg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dataMsg",b"dataMsg",u"emptyMsg",b"emptyMsg",u"header",b"header",u"msg",b"msg",u"sideChannelMsg",b"sideChannelMsg"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"msg",b"msg"]) -> typing_extensions.Literal["emptyMsg","sideChannelMsg","dataMsg"]: ...
global___UDEMessageProto = UDEMessageProto
