# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ude/ude_objects/ude.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ude.ude_objects import ude_message_pb2 as ude_dot_ude__objects_dot_ude__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ude/ude_objects/ude.proto',
  package='ude_objects',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19ude/ude_objects/ude.proto\x12\x0bude_objects\x1a!ude/ude_objects/ude_message.proto2\xa9\x04\n\x08UDEProto\x12\x44\n\x04step\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x12\x45\n\x05reset\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x12\x45\n\x05\x63lose\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x12Q\n\x11observation_space\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x12L\n\x0c\x61\x63tion_space\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x12Q\n\x11side_channel_send\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x12U\n\x13side_channel_stream\x12\x1c.ude_objects.UDEMessageProto\x1a\x1c.ude_objects.UDEMessageProto\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[ude_dot_ude__objects_dot_ude__message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_UDEPROTO = _descriptor.ServiceDescriptor(
  name='UDEProto',
  full_name='ude_objects.UDEProto',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=631,
  methods=[
  _descriptor.MethodDescriptor(
    name='step',
    full_name='ude_objects.UDEProto.step',
    index=0,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='ude_objects.UDEProto.reset',
    index=1,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='close',
    full_name='ude_objects.UDEProto.close',
    index=2,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='observation_space',
    full_name='ude_objects.UDEProto.observation_space',
    index=3,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='action_space',
    full_name='ude_objects.UDEProto.action_space',
    index=4,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='side_channel_send',
    full_name='ude_objects.UDEProto.side_channel_send',
    index=5,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='side_channel_stream',
    full_name='ude_objects.UDEProto.side_channel_stream',
    index=6,
    containing_service=None,
    input_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    output_type=ude_dot_ude__objects_dot_ude__message__pb2._UDEMESSAGEPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UDEPROTO)

DESCRIPTOR.services_by_name['UDEProto'] = _UDEPROTO

# @@protoc_insertion_point(module_scope)
