"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___UDEChannelDataTypeProto = UDEChannelDataTypeProto
class _UDEChannelDataTypeProto(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UDEChannelDataTypeProto.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    BOOLEAN = UDEChannelDataTypeProto.V(0)
    INT = UDEChannelDataTypeProto.V(1)
    FLOAT = UDEChannelDataTypeProto.V(2)
    FLOAT_LIST = UDEChannelDataTypeProto.V(3)
    STRING = UDEChannelDataTypeProto.V(4)
class UDEChannelDataTypeProto(metaclass=_UDEChannelDataTypeProto):
    V = typing.NewType('V', builtins.int)
BOOLEAN = UDEChannelDataTypeProto.V(0)
INT = UDEChannelDataTypeProto.V(1)
FLOAT = UDEChannelDataTypeProto.V(2)
FLOAT_LIST = UDEChannelDataTypeProto.V(3)
STRING = UDEChannelDataTypeProto.V(4)

class UDEBoolDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    val: builtins.bool = ...

    def __init__(self,
        *,
        val : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> None: ...
global___UDEBoolDataProto = UDEBoolDataProto

class UDEFloatDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    val: builtins.float = ...

    def __init__(self,
        *,
        val : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> None: ...
global___UDEFloatDataProto = UDEFloatDataProto

class UDEFloatListDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    val: google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float] = ...

    def __init__(self,
        *,
        val : typing.Optional[typing.Iterable[builtins.float]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> None: ...
global___UDEFloatListDataProto = UDEFloatListDataProto

class UDEIntDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    val: builtins.int = ...

    def __init__(self,
        *,
        val : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> None: ...
global___UDEIntDataProto = UDEIntDataProto

class UDEStringDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    val: typing.Text = ...

    def __init__(self,
        *,
        val : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> None: ...
global___UDEStringDataProto = UDEStringDataProto

class UDEBytesDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    val: builtins.bytes = ...

    def __init__(self,
        *,
        val : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> None: ...
global___UDEBytesDataProto = UDEBytesDataProto

class UDESideChannelMessageProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    key: typing.Text = ...
    store_local: builtins.bool = ...

    @property
    def boolVal(self) -> global___UDEBoolDataProto: ...

    @property
    def intVal(self) -> global___UDEIntDataProto: ...

    @property
    def floatVal(self) -> global___UDEFloatDataProto: ...

    @property
    def floatListVal(self) -> global___UDEFloatListDataProto: ...

    @property
    def stringVal(self) -> global___UDEStringDataProto: ...

    @property
    def bytesVal(self) -> global___UDEBytesDataProto: ...

    def __init__(self,
        *,
        key : typing.Text = ...,
        store_local : builtins.bool = ...,
        boolVal : typing.Optional[global___UDEBoolDataProto] = ...,
        intVal : typing.Optional[global___UDEIntDataProto] = ...,
        floatVal : typing.Optional[global___UDEFloatDataProto] = ...,
        floatListVal : typing.Optional[global___UDEFloatListDataProto] = ...,
        stringVal : typing.Optional[global___UDEStringDataProto] = ...,
        bytesVal : typing.Optional[global___UDEBytesDataProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"boolVal",b"boolVal",u"bytesVal",b"bytesVal",u"data",b"data",u"floatListVal",b"floatListVal",u"floatVal",b"floatVal",u"intVal",b"intVal",u"stringVal",b"stringVal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"boolVal",b"boolVal",u"bytesVal",b"bytesVal",u"data",b"data",u"floatListVal",b"floatListVal",u"floatVal",b"floatVal",u"intVal",b"intVal",u"key",b"key",u"store_local",b"store_local",u"stringVal",b"stringVal"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"data",b"data"]) -> typing_extensions.Literal["boolVal","intVal","floatVal","floatListVal","stringVal","bytesVal"]: ...
global___UDESideChannelMessageProto = UDESideChannelMessageProto
